added public APIs to change WKWebViewConfig
AzureAD/azure-activedirectory-library-for-objc pull request #1550
Opened 2020-09-20 18:31 UTC by NerevarineRule

Added public APIs on iOS & MacOS to generate custom WKWebViewConfiguration with PKeyAuth UserAgent Keyword.

Related PR: https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/848

2020-09-22 19:15 UTC, hieunguyenmsft approved these changes
Just a clarification question: I see the update only for iOS, do we need it in Mac OS too?

2020-09-22 19:16 UTC, NerevarineRule commented
@hieunguyenmsft  Thank you so much, Hieu!! :) PKeyAuth is not supported on MacOS for ADAL, while it does for MSAL :) Appreciate your question & approval.

2020-09-22 19:26 UTC, kaisong1990 approved these changes

2020-09-24 01:02 UTC, oldalton commented on ADAL/src/ADRequestParameters.h
> ++ (WKWebViewConfiguration *)defaultWKWebviewConfiguration;
Should this be added to a public ADAL header?

2020-09-24 15:18 UTC, oldalton requested changes

2020-09-24 15:18 UTC, oldalton commented on ADAL/src/public/ADAuthenticationParameters.h
> +#import "MSIDWebviewUIController.h"
We shouldn't import internal headers into public header space

2020-09-24 15:18 UTC, oldalton commented on ADAL/src/public/ADAuthenticationParameters.h
> +    Generates default WKWebviewConfiguration with "PkeyAuth/1.0" keyword appended to the UserAgent String.
I don't think this internal detail is important for the developers, and it does more than just PkeyAuth configuration (we might expand scope even more in the future)
IMO, instead we should tell that this is default recommended configuration that developers should use when they provide custom WKWebView to ADAL + point to the API that let's them provide custom webview.

2020-09-24 15:18 UTC, oldalton commented on ADAL/src/public/ADAuthenticationParameters.h
> +#if TARGET_OS_IPHONE && !MSID_EXCLUDE_WEBKIT
I think it should be available for both iOS and macOS, no?
Also, we shouldn't leak internal macro to public space (MSID_EXCLUDE_WEBKIT).

2020-09-24 19:35 UTC, oldalton commented on ADAL/src/public/ADAuthenticationContext.h
> + Likewise, on MacOS, it is recommended to configure WKWebView to use destkop content mode.
typo: destkop

2020-09-24 19:35 UTC, oldalton commented on ADAL/src/public/ADAuthenticationContext.h
> + New ADAL release has a new API "defaultWKWebviewConfiguration" that will return a default configuration object with recommended settings enabled for both iOS and MacOS.
No need to talk about new ADAL release and new API here. You can just say that [ADAuthenticationParameters defaultWKWebviewConfiguration] can be used to get a preconfigured instance of WKWebViewConfiguration.

2020-09-24 19:35 UTC, oldalton commented on changelog.txt
> +Hotfix 4.0.9 (09.23.2020)
This needs to be corrected.

2020-09-24 22:37 UTC, oldalton approved these changes

2020-09-24 22:45 UTC, merged